"""empty message

Revision ID: 08276855cc8d
Revises: 
Create Date: 2023-11-29 20:12:57.643729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08276855cc8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('emp_name', sa.String(length=100), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('request_time', sa.Date(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=False),
    sa.Column('approved_time', sa.Date(), nullable=False),
    sa.Column('manager', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('emp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
