"""empty message

Revision ID: 1ff702501255
Revises: 4db192b8ac94
Create Date: 2023-11-30 15:48:27.395496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff702501255'
down_revision = '4db192b8ac94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('emp_name', sa.String(length=100), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=False),
    sa.Column('approved_time', sa.DateTime(), nullable=False),
    sa.Column('manager', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
