"""empty message

Revision ID: 43399ad92152
Revises: 50cc049db297
Create Date: 2023-12-26 16:50:29.781602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43399ad92152'
down_revision = '50cc049db297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('exit_out')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_out', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('exit_time')

    # ### end Alembic commands ###
