"""empty message

Revision ID: 4db192b8ac94
Revises: 9d71389e7e10
Create Date: 2023-11-30 15:26:23.640479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4db192b8ac94'
down_revision = '9d71389e7e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('request_time')
        batch_op.drop_column('approved_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('request_time', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('approved_by',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
