"""empty message

Revision ID: 50cc049db297
Revises: e92ea9527d38
Create Date: 2023-12-26 16:36:27.600703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50cc049db297'
down_revision = 'e92ea9527d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
