"""empty message

Revision ID: a0a1de45e73b
Revises: 1ff702501255
Create Date: 2023-11-30 15:51:08.264474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a1de45e73b'
down_revision = '1ff702501255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_index('emp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.create_index('emp_id', ['emp_id'], unique=False)

    # ### end Alembic commands ###
