"""empty message

Revision ID: a5e5284a6655
Revises: 83ad14b705bf
Create Date: 2023-11-30 12:16:07.178132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e5284a6655'
down_revision = '83ad14b705bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index('emp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index('emp_id', ['emp_id'], unique=False)

    # ### end Alembic commands ###
